# BungeeUtilities by Daarkii

# Insert your Mysql data if you want to use it
mysql:
  host: localhost
  port: '3306'
  user: 'admin'
  password: ''
  maxConnections: 10

# Insert your MongoDB data if you want to use it
mongo:
  # Change this to false if your Mongo database is not on the same server
  isOnLocalhost: true
  host: localhost
  port: '27017'
  # You don't need to insert the user and the password if your mongo database is on the same server
  # This will be ignored if "isOnLocalhost" is true
  user: 'admin'
  password: ''

# Select you storage provider here (mysql or mongodb)
plugins:
  dbutilities:
    storage: mysql
    database: bungee
