# BungeeUtilities by Daarkii

# Set this to true if you want that every step will be logged in the console
debug: false

# Select your language here. Look into the messages' folder for available languages and names
language: "en_EN"